"""
工具错误码标准定义
规范: ERR_MODULE_OPERATION_DETAIL
小健 2026-05-21
"""
from enum import Enum

class ToolErrorCode(str, Enum):
    # FILE模块
    FILE_NOT_FOUND = "ERR_FILE_NOT_FOUND"
    FILE_MOVE_FAILED = "ERR_FILE_MOVE_FAILED"
    FILE_READ_PERMISSION = "ERR_FILE_READ_PERMISSION"
    FILE_WRITE_PERMISSION = "ERR_FILE_WRITE_PERMISSION"
    FILE_INVALID_PATH = "ERR_FILE_INVALID_PATH"
    FILE_JSON_PARSE_ERROR = "ERR_FILE_JSON_PARSE_ERROR"
    FILE_DIRECTORY_NOT_FOUND = "ERR_FILE_DIRECTORY_NOT_FOUND"
    FILE_SEARCH_NO_MATCH = "ERR_FILE_SEARCH_NO_MATCH"
    FILE_RENAME_FAILED = "ERR_FILE_RENAME_FAILED"
    FILE_ARCHIVE_FAILED = "ERR_FILE_ARCHIVE_FAILED"
    
    # DOCUMENT模块
    DOC_UNSUPPORTED_FORMAT = "ERR_DOC_UNSUPPORTED_FORMAT"
    DOC_READ_FAILED = "ERR_DOC_READ_FAILED"
    DOC_WRITE_FAILED = "ERR_DOC_WRITE_FAILED"
    DOC_JSON_MISSING = "ERR_DOC_JSON_MISSING"
    DOC_CHART_INVALID_DATA = "ERR_DOC_CHART_INVALID_DATA"
    DOC_ANALYZE_FAILED = "ERR_DOC_ANALYZE_FAILED"
    DOC_FILTER_INVALID_COLUMN = "ERR_DOC_FILTER_INVALID_COLUMN"
    DOC_SQL_EXECUTION_FAILED = "ERR_DOC_SQL_EXECUTION_FAILED"
    DOC_TABLE_NOT_FOUND = "ERR_DOC_TABLE_NOT_FOUND"
    
    # SHELL模块
    SHELL_TIMEOUT = "ERR_SHELL_TIMEOUT"
    SHELL_COMMAND_NOT_FOUND = "ERR_SHELL_COMMAND_NOT_FOUND"
    SHELL_EXECUTION_FAILED = "ERR_SHELL_EXECUTION_FAILED"
    SHELL_SYNTAX_ERROR = "ERR_SHELL_SYNTAX_ERROR"
    SHELL_UNSAFE = "ERR_SHELL_UNSAFE"
    SHELL_SESSION_NOT_FOUND = "ERR_SHELL_SESSION_NOT_FOUND"
    
    # NETWORK模块
    NET_REQUEST_FAILED = "ERR_NET_REQUEST_FAILED"
    NET_TIMEOUT = "ERR_NET_TIMEOUT"
    NET_INVALID_URL = "ERR_NET_INVALID_URL"
    NET_FETCH_FAILED = "ERR_NET_FETCH_FAILED"
    NET_PING_FAILED = "ERR_NET_PING_FAILED"
    NET_PORT_CHECK_FAILED = "ERR_NET_PORT_CHECK_FAILED"
    
    # META模块
    META_TIME_INVALID_VALUE = "ERR_META_TIME_INVALID_VALUE"
    META_TIME_UNSUPPORTED_ACTION = "ERR_META_TIME_UNSUPPORTED_ACTION"
    META_TIMER_INVALID_DELAY = "ERR_META_TIMER_INVALID_DELAY"
    META_TIMER_MISSING_CALLBACK = "ERR_META_TIMER_MISSING_CALLBACK"
    META_TOOL_NOT_FOUND = "ERR_META_TOOL_NOT_FOUND"
    META_PIPELINE_FAILED = "ERR_META_PIPELINE_FAILED"
    
    # DESKTOP模块
    DESKTOP_WINDOW_NOT_FOUND = "ERR_DESKTOP_WINDOW_NOT_FOUND"
    DESKTOP_OCR_FAILED = "ERR_DESKTOP_OCR_FAILED"
    DESKTOP_SCREEN_CAPTURE_FAILED = "ERR_DESKTOP_SCREEN_CAPTURE_FAILED"
    DESKTOP_MISSING_DEPENDENCY = "ERR_DESKTOP_MISSING_DEPENDENCY"
    DESKTOP_CLIPBOARD_INVALID_ACTION = "ERR_DESKTOP_CLIPBOARD_INVALID_ACTION"
    DESKTOP_MOUSE_FAILED = "ERR_DESKTOP_MOUSE_FAILED"
    DESKTOP_KEYBOARD_FAILED = "ERR_DESKTOP_KEYBOARD_FAILED"
    
    # SYSTEM模块
    SYS_PROCESS_NOT_FOUND = "ERR_SYS_PROCESS_NOT_FOUND"
    SYS_ENV_INVALID_NAME = "ERR_SYS_ENV_INVALID_NAME"
    SYS_ENV_MISSING_NAME = "ERR_SYS_ENV_MISSING_NAME"
    SYS_EVENT_LOG_FAILED = "ERR_SYS_EVENT_LOG_FAILED"
    SYS_SERVICE_FAILED = "ERR_SYS_SERVICE_FAILED"
    SYS_REGISTRY_FAILED = "ERR_SYS_REGISTRY_FAILED"
    
    # 通用错误
    PARAMETER_MISSING = "ERR_PARAMETER_MISSING"
    PARAMETER_INVALID = "ERR_PARAMETER_INVALID"
    UNKNOWN_ERROR = "ERR_UNKNOWN_ERROR"
