[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
timeout = 2000
markers =
    e2e_full_link: full link E2E test
    asyncio: asyncio test