"""
批量修复ERR code脚本 - 将所有ERR code统一为三段式规范
小健 2026-05-21
"""
import pathlib
import re

# 修复规则表：{旧code: 新code}
FIXES = {
    # desktop模块
    'ERR_GET_WINDOW_POSITION': 'ERR_DESKTOP_GET_WINDOW_INFO',
    'ERR_GET_WINDOW_INFO': 'ERR_DESKTOP_GET_WINDOW_INFO',
    'ERR_GET_MOUSE_POSITION': 'ERR_DESKTOP_GET_MOUSE_POSITION',
    'ERR_CHECK_SCREEN_SIZE': 'ERR_DESKTOP_CHECK_SCREEN_SIZE',
    'ERR_CHECK_WINDOW': 'ERR_DESKTOP_CHECK_WINDOW',
    'ERR_CHECK_TESSERACT': 'ERR_DESKTOP_CHECK_TESSERACT',
    'ERR_NO_DEPENDENCY': 'ERR_DESKTOP_NO_DEPENDENCY',
    'ERR_NOT_WINDOWS': 'ERR_DESKTOP_NOT_WINDOWS',
    'ERR_NO_PYWIN32': 'ERR_DESKTOP_NO_PYWIN32',
    'ERR_PLATFORM_NOT_SUPPORTED': 'ERR_DESKTOP_PLATFORM_NOT_SUPPORTED',
    'ERR_CLIPBOARD': 'ERR_DESKTOP_CLIPBOARD',
    'ERR_CLICK': 'ERR_DESKTOP_MOUSE_CLICK',
    'ERR_SCROLL': 'ERR_DESKTOP_MOUSE_SCROLL',
    'ERR_WINDOW_NOT_FOUND': 'ERR_DESKTOP_WINDOW_NOT_FOUND',
    'ERR_WINDOW_SET_STATE': 'ERR_DESKTOP_WINDOW_SET_STATE',
    'ERR_WINDOW_RESIZE': 'ERR_DESKTOP_WINDOW_RESIZE',
    'ERR_FOCUS_WINDOW': 'ERR_DESKTOP_FOCUS_WINDOW',
    'ERR_KEYBOARD_TYPE': 'ERR_DESKTOP_KEYBOARD_TYPE',
    'ERR_KEYBOARD_SHORTCUT': 'ERR_DESKTOP_KEYBOARD_SHORTCUT',
    'ERR_KEY_COMBO': 'ERR_DESKTOP_KEY_COMBO',
    'ERR_SCREENSHOT': 'ERR_DESKTOP_SCREENSHOT',
    'ERR_SCREEN_SNAPSHOT': 'ERR_DESKTOP_SCREENSHOT',
    'ERR_SCREEN_RECORD': 'ERR_DESKTOP_SCREEN_RECORD',
    'ERR_OCR_FAILED': 'ERR_DESKTOP_OCR_FAILED',
    'ERR_SCREEN_CAPTURE_FAILED': 'ERR_DESKTOP_SCREEN_CAPTURE_FAILED',
    
    # document模块
    'ERR_ANALYZE_DATA': 'ERR_DOC_ANALYZE_DATA',
    'ERR_CHART_GENERATE': 'ERR_DOC_CHART_GENERATE',
    'ERR_NO_OPENPYXL': 'ERR_DOC_NO_OPENPYXL',
    'ERR_UNSUPPORTED_FORMAT': 'ERR_DOC_UNSUPPORTED_FORMAT',
    'ERR_READ_CSV': 'ERR_DOC_READ_CSV',
    'ERR_READ_DOCX': 'ERR_DOC_READ_DOCX',
    'ERR_READ_PDF': 'ERR_DOC_READ_PDF',
    'ERR_READ_XLSX': 'ERR_DOC_READ_XLSX',
    'ERR_READ_JSON': 'ERR_DOC_READ_JSON',
    'ERR_READ_PPTX': 'ERR_DOC_READ_PPTX',
    'ERR_WRITE_DOCX': 'ERR_DOC_WRITE_DOCX',
    'ERR_WRITE_PDF': 'ERR_DOC_WRITE_PDF',
    'ERR_WRITE_XLSX': 'ERR_DOC_WRITE_XLSX',
    'ERR_WRITE_PPTX': 'ERR_DOC_WRITE_PPTX',
    'ERR_WRITE_TOML': 'ERR_DOC_WRITE_TOML',
    'ERR_WRITE_YAML': 'ERR_DOC_WRITE_YAML',
    'ERR_WRITE_JSON': 'ERR_DOC_WRITE_JSON',
    'ERR_EMPTY_QUERY': 'ERR_DOC_QUERY_EMPTY',
    'ERR_DB_TABLE_NOT_FOUND': 'ERR_DOC_DB_TABLE_NOT_FOUND',
    'ERR_DB_CONNECTION': 'ERR_DB_CONNECTION',
    'ERR_DB_EXEC_FAILED': 'ERR_DOC_DB_EXEC_FAILED',
    'ERR_GET_DB_SCHEMA': 'ERR_DOC_DB_SCHEMA',
    'ERR_QUERY_FAILED': 'ERR_DOC_QUERY_FAILED',
    'ERR_SCHEMA_FAILED': 'ERR_DOC_SCHEMA_FAILED',
    'ERR_SQL_EXEC': 'ERR_DOC_SQL_EXEC',
    'ERR_FILTER_INVALID': 'ERR_DOC_FILTER_INVALID',
    
    # file模块
    'ERR_BINARY_FILE': 'ERR_FILE_READ_BINARY_FILE',
    'ERR_FILE_NOT_FOUND': 'ERR_FILE_NOT_FOUND',
    'ERR_FILE_TOO_LARGE': 'ERR_FILE_READ_TOO_LARGE',
    'ERR_CHECKSUM_FAILED': 'ERR_FILE_CHECKSUM_FAILED',
    'ERR_COMPRESS_FAILED': 'ERR_FILE_COMPRESS_FAILED',
    'ERR_COPY_FAILED': 'ERR_FILE_COPY_FAILED',
    'ERR_MOVE': 'ERR_FILE_MOVE_FAILED',
    'ERR_LIST_DIR_FAILED': 'ERR_FILE_LIST_DIR_FAILED',
    'ERR_PATH_NOT_DIR': 'ERR_FILE_PATH_NOT_DIR',
    'ERR_DIR_NOT_FOUND': 'ERR_FILE_DIRECTORY_NOT_FOUND',
    'ERR_CONTENT_BLOCKED': 'ERR_FILE_CONTENT_BLOCKED',
    'ERR_CONTENT_INVALID': 'ERR_FILE_CONTENT_INVALID',
    'ERR_DATA_PROTECTION': 'ERR_FILE_DATA_PROTECTION',
    'ERR_CHECK_PERMISSION': 'ERR_FILE_CHECK_PERMISSION',
    'ERR_FORMAT_NOT_DETECTED': 'ERR_DOC_FORMAT_NOT_DETECTED',
    'ERR_FORMAT_NOT_SUPPORTED': 'ERR_DOC_FORMAT_NOT_SUPPORTED',
    'ERR_DATA_FORMAT_FAILED': 'ERR_DOC_DATA_FORMAT_FAILED',
    'ERR_FILE_EXISTS': 'ERR_FILE_PATH_EXISTS',
    'ERR_FILE_INFO': 'ERR_FILE_INFO',
    'ERR_PATH_NOT_FILE': 'ERR_FILE_PATH_NOT_FILE',
    'ERR_READ_ONLY_VIOLATION': 'ERR_FILE_READ_ONLY_VIOLATION',
    'ERR_RENAME_FAILED': 'ERR_FILE_RENAME_FAILED',
    'ERR_ARCHIVE_FAILED': 'ERR_FILE_ARCHIVE_FAILED',
    'ERR_SEARCH_FILE': 'ERR_FILE_SEARCH_NO_MATCH',
    'ERR_READ_DATA_FILE': 'ERR_FILE_READ_DATA_FILE',
    
    # shell模块
    'ERR_EMPTY_PARAM': 'ERR_PARAMETER_EMPTY',
    'ERR_INVALID_PARAM': 'ERR_PARAMETER_INVALID',
    'ERR_TIMEOUT': 'ERR_SHELL_TIMEOUT',
    'ERR_SERVICE_TIMEOUT': 'ERR_SHELL_TIMEOUT',
    'ERR_SERVICE_COMMAND_NOT_FOUND': 'ERR_SHELL_COMMAND_NOT_FOUND',
    'ERR_SERVICE_LIST': 'ERR_SHELL_SERVICE_LIST',
    'ERR_SERVICE_START': 'ERR_SHELL_SERVICE_START',
    'ERR_SERVICE_STOP': 'ERR_SHELL_SERVICE_STOP',
    'ERR_SERVICE_NOT_FOUND': 'ERR_SHELL_SERVICE_NOT_FOUND',
    'ERR_SYSTEM_COMMAND_NOT_FOUND': 'ERR_SHELL_COMMAND_NOT_FOUND',
    'ERR_TASK_COMMAND_NOT_FOUND': 'ERR_SHELL_COMMAND_NOT_FOUND',
    'ERR_TASK_TIMEOUT': 'ERR_SHELL_TIMEOUT',
    'ERR_TASK_CREATE': 'ERR_META_TASK_CREATE',
    'ERR_TASK_DELETE': 'ERR_META_TASK_DELETE',
    'ERR_TASK_EMPTY': 'ERR_META_TASK_EMPTY',
    'ERR_TASK_LIST': 'ERR_META_TASK_LIST',
    'ERR_TASK_NOT_FOUND': 'ERR_META_TASK_NOT_FOUND',
    'ERR_SHELL_INJECTION': 'ERR_SHELL_INJECTION',
    'ERR_EXEC_EMPTY_CODE': 'ERR_SHELL_EXEC_EMPTY_CODE',
    'ERR_EXEC_INVALID_DIR': 'ERR_SHELL_EXEC_INVALID_DIR',
    'ERR_EXEC_NODE_NOT_FOUND': 'ERR_SHELL_EXEC_NODE_NOT_FOUND',
    'ERR_EXEC_PYTHON_NOT_FOUND': 'ERR_SHELL_EXEC_PYTHON_NOT_FOUND',
    'ERR_EXECUTE_SHELL': 'ERR_SHELL_EXECUTE_SHELL',
    'ERR_EXECUTE_PYTHON': 'ERR_SHELL_EXEC_PYTHON',
    'ERR_EXECUTE_JS': 'ERR_SHELL_EXEC_JS',
    'ERR_EXEC_FAILED': 'ERR_SHELL_EXEC_FAILED',
    'ERR_EXEC_JS': 'ERR_SHELL_EXEC_JS',
    'ERR_EXEC_PYTHON': 'ERR_SHELL_EXEC_PYTHON',
    'ERR_EXEC_TIMEOUT': 'ERR_SHELL_TIMEOUT',
    'ERR_SHELL_COMMAND_NOT_FOUND': 'ERR_SHELL_COMMAND_NOT_FOUND',
    'ERR_NETWORK_COMMAND_NOT_FOUND': 'ERR_SHELL_COMMAND_NOT_FOUND',
    'ERR_NETWORK_GET': 'ERR_NET_GET',
    'ERR_NETWORK_POST': 'ERR_NET_POST',
    'ERR_NETWORK_INVALID_URL': 'ERR_NET_INVALID_URL',
    'ERR_NETWORK_UNKNOWN': 'ERR_NET_UNKNOWN',
    'ERR_NETWORK_TIMEOUT': 'ERR_NET_TIMEOUT',
    'ERR_SYSTEM_TIMEOUT': 'ERR_SHELL_TIMEOUT',
    
    # meta模块
    'ERR_TIME_FORMAT': 'ERR_META_TIME_FORMAT',
    'ERR_TIME_LOCAL_TO_UTC': 'ERR_META_TIME_CONVERT',
    'ERR_TIME_UTC_TO_LOCAL': 'ERR_META_TIME_CONVERT',
    'ERR_TIME_NEXT_N_WORKDAY': 'ERR_META_CALENDAR_NEXT_N_WORKDAY',
    'ERR_TIME_ADD': 'ERR_META_TIME_ADD',
    'ERR_TIME_DIFF': 'ERR_META_TIME_DIFF',
    'ERR_TIME_TO_TIMESTAMP': 'ERR_META_TIME_TO_TIMESTAMP',
    'ERR_TIME_NOW': 'ERR_META_TIME_NOW',
    'ERR_TIME_TZ': 'ERR_META_TIME_TZ',
    'ERR_TIME_DATE': 'ERR_META_TIME_DATE',
    'ERR_TIMESTAMP_TO_TIME': 'ERR_META_TIME_CONVERT',
    'ERR_INVALID_CHECK_TYPE': 'ERR_META_INVALID_CHECK_TYPE',
    'ERR_NO_TASK': 'ERR_META_NO_TASK',
    'ERR_NO_ACTIVE_TASK': 'ERR_META_NO_ACTIVE_TASK',
    'ERR_TOOL_IMPL_NOT_FOUND': 'ERR_META_TOOL_IMPL_NOT_FOUND',
    'ERR_REGISTER_MISSING': 'ERR_META_TOOL_REGISTER_MISSING',
    'ERR_PIPELINE_FAILED': 'ERR_META_PIPELINE_FAILED',
    'ERR_PIPELINE_STOPPED': 'ERR_META_PIPELINE_STOPPED',
    'ERR_TOOL_NOT_FOUND': 'ERR_META_TOOL_NOT_FOUND',
    'ERR_TOOL_SEARCH': 'ERR_META_TOOL_SEARCH',
    'ERR_TIMER_SET': 'ERR_META_TIMER_SET',
    'ERR_TIMER_CLEAR': 'ERR_META_TIMER_CLEAR',
    'ERR_TIMER_LIST': 'ERR_META_TIMER_LIST',
    'ERR_TIMER_PARAM': 'ERR_META_TIMER_PARAM',
    'ERR_TIMEZONE_CONVERT': 'ERR_META_TIMEZONE_CONVERT',
    
    # system模块
    'ERR_ENV_GET': 'ERR_SYS_ENV_GET',
    'ERR_ENV_LIST': 'ERR_SYS_ENV_LIST',
    'ERR_ENV_SET': 'ERR_SYS_ENV_SET',
    'ERR_ENV_INVALID_ACTION': 'ERR_SYS_ENV_INVALID_ACTION',
    'ERR_ENV_INVALID_NAME': 'ERR_SYS_ENV_INVALID_NAME',
    'ERR_ENV_INVALID_SCOPE': 'ERR_SYS_ENV_INVALID_SCOPE',
    'ERR_ENV_INVALID_VALUE': 'ERR_SYS_ENV_INVALID_VALUE',
    'ERR_GET': 'ERR_SYS_ENV_GET',
    'ERR_REG_INVALID_ROOT_KEY': 'ERR_SYS_REG_INVALID_ROOT_KEY',
    'ERR_REG_KEY_NOT_FOUND': 'ERR_SYS_REG_KEY_NOT_FOUND',
    'ERR_REG_KEY_NOT_EMPTY': 'ERR_SYS_REG_KEY_NOT_EMPTY',
    'ERR_REG_CANNOT_DELETE_ROOT': 'ERR_SYS_REG_CANNOT_DELETE_ROOT',
    'ERR_REG_DELETE_FAILED': 'ERR_SYS_REG_DELETE_FAILED',
    'ERR_REG_INVALID_PARAM': 'ERR_SYS_REG_INVALID_PARAM',
    'ERR_REG_PERMISSION_DENIED': 'ERR_REG_PERMISSION_DENIED',
    'ERR_REG_READ_FAILED': 'ERR_SYS_REG_READ_FAILED',
    'ERR_REG_UNSUPPORTED_TYPE': 'ERR_REG_UNSUPPORTED_TYPE',
    'ERR_REG_WRITE_FAILED': 'ERR_SYS_REG_WRITE_FAILED',
    'ERR_REG_VALIDATE_FAILED': 'ERR_SYS_REG_VALIDATE_FAILED',
    'ERR_SYSTEM_INFO': 'ERR_SYS_SYSTEM_INFO',
    'ERR_INVALID_PARAM': 'ERR_PARAMETER_INVALID',
    'ERR_PARAMETER_INVALID': 'ERR_PARAMETER_INVALID',
    'ERR_PARAMETER_MISSING': 'ERR_PARAMETER_MISSING',
    'ERR_INVALID_VALUE': 'ERR_PARAMETER_INVALID',
    
    # 通用
    'ERR_INVALID_ACTION': 'ERR_INVALID_ACTION',
    'ERR_INVALID_JSON': 'ERR_PARAMETER_INVALID',
    'ERR_INVALID_FORMAT': 'ERR_PARAMETER_INVALID',
    'ERR_INVALID_MODE': 'ERR_PARAMETER_INVALID',
    'ERR_INVALID_PARAMS': 'ERR_PARAMETER_INVALID',
    'ERR_INVALID_STEP': 'ERR_PARAMETER_INVALID',
    'ERR_MISSING_PARAM': 'ERR_PARAMETER_MISSING',
    'ERR_MISSING_TOOL': 'ERR_PARAMETER_MISSING',
    'ERR_UNSAFE_CODE': 'ERR_SHELL_UNSAFE',
}

def main():
    tools_dir = pathlib.Path('app/services/tools')
    total_fixes = 0
    modified_files = []
    
    for py_file in tools_dir.rglob('*.py'):
        if '__pycache__' in str(py_file):
            continue
        
        content = py_file.read_text(encoding='utf-8')
        original = content
        
        # 应用所有修复规则
        for old_code, new_code in FIXES.items():
            old_pattern = f'"code": "{old_code}"'
            new_pattern = f'"code": "{new_code}"'
            content = content.replace(old_pattern, new_pattern)
        
        if content != original:
            py_file.write_text(content, encoding='utf-8')
            modified_files.append(py_file.relative_to('app/services/tools'))
            total_fixes += 1
    
    print(f'修复完成: {total_fixes} 个文件被修改')
    if modified_files:
        print(f'\n修改的文件:')
        for f in modified_files:
            print(f'  {f}')

if __name__ == '__main__':
    main()
