# -*- coding: utf-8 -*-
"""
系统常量集中管理 — 小健 2026-05-24

所有跨模块共享的常量统一定义在此，消除散落和重复。
按功能分组：HTTP/错误码、重试/限流、网络/超时、内容截断、错误类型。
"""

# ============================================================
# 1. HTTP 状态码与错误码
# ============================================================

HTTP_RATE_LIMIT = 429
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500
HTTP_BAD_GATEWAY = 502
HTTP_SERVICE_UNAVAILABLE = 503
HTTP_GATEWAY_TIMEOUT = 504
HTTP_TIMEOUT_BROKEN = 524

RATE_LIMIT_STATUS_CODES = {HTTP_RATE_LIMIT, 1305}

RETRYABLE_HTTP_STATUS_CODES = {HTTP_RATE_LIMIT, HTTP_INTERNAL_ERROR, HTTP_BAD_GATEWAY, HTTP_SERVICE_UNAVAILABLE, HTTP_GATEWAY_TIMEOUT}

# ============================================================
# 2. 重试与限流
# ============================================================

DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 2.0
DEFAULT_BACKOFF_FACTOR = 2.0

DEFAULT_RETRYABLE_ERRORS = ["timeout", "network_error"]

CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_RECOVERY_TIMEOUT = 60.0
CIRCUIT_BREAKER_SUCCESS_THRESHOLD = 3

DEFAULT_MAX_STEPS = 100
MAX_CONSECUTIVE_CHUNKS = 5

# ============================================================
# 3. 网络与超时
# ============================================================

DEFAULT_LLM_TIMEOUT = 60
DEFAULT_READ_TIMEOUT = 60.0
DEFAULT_CONNECT_TIMEOUT = 30.0
DEFAULT_WRITE_TIMEOUT = 10.0
DEFAULT_POOL_TIMEOUT = 10.0
DEFAULT_PROBE_TIMEOUT = 15
DEFAULT_API_TEST_TIMEOUT = 30.0

LLM_MAX_CONNECTIONS = 10
LLM_MAX_KEEPALIVE = 5
API_TEST_MAX_CONNECTIONS = 5
API_TEST_MAX_KEEPALIVE = 2
# NETWORK_TOOL_MAX_* 已迁移到 tool_constants.py (NETWORK_MAX_CONNECTIONS/NETWORK_MAX_KEEPALIVE)

BROWSER_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

DEFAULT_CORS_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000"

# ============================================================
# 4. 内容截断与字符限制
# ============================================================

MAX_CONTEXT_CHARS = 150000
TEMP_HISTORY_CHAR_LIMIT = 50000
OBSERVATION_BUDGET_DECAY = 10000
OBSERVATION_BUDGET_MIN = 20000
OBSERVATION_BUDGET_MAX = 50000

DEFAULT_MAX_OUTPUT_CHARS = 5000
DEFAULT_MAX_FILE_CHARS = 8000
DEFAULT_MAX_DOC_CHARS = 10000
DEFAULT_MAX_CLIPBOARD_CHARS = 5000
DEFAULT_MAX_ENV_VALUE_CHARS = 1000
DEFAULT_MAX_DATA_CHARS = 1000000
DEFAULT_MAX_LIST_ITEMS = 10000

MAX_CHUNK_COUNT = 5000
MAX_EMPTY_CONTENT_COUNT = 100
LOG_PREVIEW_CHARS = 500
DATA_TOO_LARGE_THRESHOLD = 10000

# ============================================================
# 5. 错误类型常量
# ============================================================

ERROR_TYPE_NETWORK_ERROR = "network_error"
ERROR_TYPE_TIMEOUT = "timeout"
ERROR_TYPE_IDLE_TIMEOUT = "idle_timeout"
ERROR_TYPE_RATE_LIMIT = "rate_limit"
ERROR_TYPE_EMPTY_RESPONSE = "empty_response"
ERROR_TYPE_RETRY_FAILED = "retry_failed"
ERROR_TYPE_THOUGHT_ONLY = "thought_only"
ERROR_TYPE_JSON_PARSE_ERROR = "json_parse_error"
ERROR_TYPE_API_LIMIT = "api_limit"
ERROR_TYPE_DATA_TOO_LARGE = "data_too_large"
ERROR_TYPE_UNKNOWN = "unknown"

API_ERROR_PREFIX = "api_error_"
API_ERROR_429 = "api_error_429"
API_ERROR_400 = "api_error_400"
API_ERROR_401 = "api_error_401"
API_ERROR_403 = "api_error_403"
API_ERROR_500 = "api_error_500"
API_ERROR_502 = "api_error_502"
API_ERROR_503 = "api_error_503"
API_ERROR_504 = "api_error_504"
API_ERROR_524 = "api_error_524"

# ============================================================
# 6. HTTP状态码 → 错误类型 映射表
# ============================================================

HTTP_STATUS_TO_ERROR_TYPE = {
    HTTP_RATE_LIMIT: API_ERROR_429,
    HTTP_SERVICE_UNAVAILABLE: API_ERROR_503,
    HTTP_TIMEOUT_BROKEN: API_ERROR_524,
    HTTP_INTERNAL_ERROR: API_ERROR_500,
    HTTP_BAD_GATEWAY: API_ERROR_502,
    HTTP_GATEWAY_TIMEOUT: API_ERROR_504,
    HTTP_UNAUTHORIZED: API_ERROR_401,
    HTTP_FORBIDDEN: API_ERROR_403,
    HTTP_BAD_REQUEST: API_ERROR_400,
}

# ============================================================
# 7. CRSS评分常量
# ============================================================

CRSS_DANGEROUS_COMMAND_BONUS = 3.0  # 危险命令额外加分
CRSS_ACTION_MODULATION_FACTOR = 0.3  # 动作兼容调制因子
CRSS_ACTION_INFERENCE_WEIGHT = 0.5  # 动作推类型权重

# ============================================================
# 8. 工具结果状态码 — 小沈 2026-05-27
# ============================================================

SUCCESS_CODE = "SUCCESS"
LLM_SAFE_LIMIT = 100_000

# ============================================================
# 9. 工具错误码常量 — 小沈 2026-05-26
#     命名规范: ERR_{MODULE}_{PROBLEM}
#     MODULE: DOC/FILE/SHELL/META/SYSTEM/DESKTOP/NETWORK/DB/REG/TIMER/TASK/WIN/SYS_ENV/SYS_REG
#     所有工具返回的错误码统一定义在此，消除散落和命名不一致
# ============================================================

# --- 文档/格式类 ---
ERR_DOC_FORMAT_NOT_SUPPORTED = "ERR_DOC_FORMAT_NOT_SUPPORTED"
ERR_DOC_READ_JSON = "ERR_DOC_READ_JSON"
ERR_DOC_PARSE_FAILED = "ERR_DOC_PARSE_FAILED"

# --- 文件操作类 ---
ERR_FILE_NOT_FOUND = "ERR_FILE_NOT_FOUND"
ERR_FILE_EXISTS = "ERR_FILE_EXISTS"
ERR_FILE_PATH_INVALID = "ERR_FILE_PATH_INVALID"
ERR_FILE_PATH_NOT_DIR = "ERR_FILE_PATH_NOT_DIR"
ERR_FILE_DIRECTORY_NOT_FOUND = "ERR_FILE_DIRECTORY_NOT_FOUND"
ERR_FILE_READ = "ERR_FILE_READ"
ERR_FILE_READ_FAILED = "ERR_FILE_READ_FAILED"
ERR_FILE_READ_BINARY_FILE = "ERR_FILE_READ_BINARY_FILE"
ERR_FILE_READ_TOO_LARGE = "ERR_FILE_READ_TOO_LARGE"
ERR_FILE_WRITE_FAILED = "ERR_FILE_WRITE_FAILED"
ERR_FILE_REPLACE_FAILED = "ERR_FILE_REPLACE_FAILED"
ERR_FILE_SEARCH_FAILED = "ERR_FILE_SEARCH_FAILED"
ERR_FILE_RENAME_FAILED = "ERR_FILE_RENAME_FAILED"

# --- Shell/命令执行类 ---
ERR_SHELL_TIMEOUT = "ERR_SHELL_TIMEOUT"
ERR_SHELL_COMMAND_NOT_FOUND = "ERR_SHELL_COMMAND_NOT_FOUND"
ERR_SHELL_NOT_FOUND = "ERR_SHELL_NOT_FOUND"
ERR_SHELL_EXEC = "ERR_SHELL_EXEC"
ERR_SHELL_EXEC_EMPTY_CODE = "ERR_SHELL_EXEC_EMPTY_CODE"
ERR_SHELL_EXEC_INVALID_DIR = "ERR_SHELL_EXEC_INVALID_DIR"
ERR_SHELL_EXEC_NODE_NOT_FOUND = "ERR_SHELL_EXEC_NODE_NOT_FOUND"
ERR_SHELL_EXEC_PYTHON_NOT_FOUND = "ERR_SHELL_EXEC_PYTHON_NOT_FOUND"
ERR_SHELL_FIND_COMMAND = "ERR_SHELL_FIND_COMMAND"
ERR_SHELL_GET_CWD = "ERR_SHELL_GET_CWD"
ERR_SHELL_INJECTION = "ERR_SHELL_INJECTION"
ERR_SHELL_CHECK_PATH = "ERR_SHELL_CHECK_PATH"
ERR_SHELL_CHECK_RUNNING = "ERR_SHELL_CHECK_RUNNING"
ERR_SHELL_EXCEPTION = "ERR_SHELL_EXCEPTION"
ERR_SHELL_VALIDATE_COMMAND = "ERR_SHELL_VALIDATE_COMMAND"

# --- 参数/输入校验类 ---
ERR_PARAM_INVALID = "ERR_PARAM_INVALID"
ERR_PARAM_MISSING = "ERR_PARAM_MISSING"
ERR_PARAM_CONFLICT = "ERR_PARAM_CONFLICT"
ERR_PARAMETER_INVALID = "ERR_PARAMETER_INVALID"
ERR_PARAMETER_EMPTY = "ERR_PARAMETER_EMPTY"
ERR_PARAMETER_MISSING = "ERR_PARAMETER_MISSING"

# --- Meta/任务/时间类 ---
ERR_META_NO_ACTIVE_TASK = "ERR_META_NO_ACTIVE_TASK"
ERR_META_INVALID_FORMAT = "ERR_META_INVALID_FORMAT"
ERR_TASK_CREATE = "ERR_TASK_CREATE"
ERR_TASK_DELETE = "ERR_TASK_DELETE"
ERR_TASK_EMPTY = "ERR_TASK_EMPTY"
ERR_TASK_LIST = "ERR_TASK_LIST"
ERR_TASK_NOT_FOUND = "ERR_TASK_NOT_FOUND"
ERR_TIMER_SET = "ERR_TIMER_SET"
ERR_TIMER_CLEAR = "ERR_TIMER_CLEAR"
ERR_TIMER_LIST = "ERR_TIMER_LIST"
ERR_TIMER_PARAM = "ERR_TIMER_PARAM"
ERR_TIMESTAMP_TO_TIME = "ERR_TIMESTAMP_TO_TIME"
ERR_TIME_ADD = "ERR_TIME_ADD"
ERR_TIME_DATE = "ERR_TIME_DATE"
ERR_TIME_DIFF = "ERR_TIME_DIFF"
ERR_TIME_NOW = "ERR_TIME_NOW"
ERR_TIME_TO_TIMESTAMP = "ERR_TIME_TO_TIMESTAMP"
ERR_TIME_TZ = "ERR_TIME_TZ"

# --- 网络/URL类 ---
ERR_INVALID_URL = "ERR_INVALID_URL"
ERR_NETWORK_REQUEST = "ERR_NETWORK_REQUEST"
ERR_NETWORK_TIMEOUT = "ERR_NETWORK_TIMEOUT"
ERR_NETWORK_DNS = "ERR_NETWORK_DNS"
ERR_NETWORK_CONNECT = "ERR_NETWORK_CONNECT"

# --- 系统/进程/服务类 ---
ERR_SYSTEM_TIMEOUT = "ERR_SYSTEM_TIMEOUT"
ERR_SYSTEM_PROCESS_LIST = "ERR_SYSTEM_PROCESS_LIST"
ERR_SYSTEM_PROCESS_KILL = "ERR_SYSTEM_PROCESS_KILL"
ERR_SYSTEM_COMMAND_NOT_FOUND = "ERR_SYSTEM_COMMAND_NOT_FOUND"
ERR_SYSTEM_INFO = "ERR_SYSTEM_INFO"
ERR_SYSTEM_EVENT_LOG = "ERR_SYSTEM_EVENT_LOG"
ERR_SYSTEM_NET_CONN = "ERR_SYSTEM_NET_CONN"
ERR_SERVICE_LIST = "ERR_SERVICE_LIST"
ERR_SERVICE_NOT_FOUND = "ERR_SERVICE_NOT_FOUND"
ERR_SERVICE_START = "ERR_SERVICE_START"
ERR_SERVICE_STOP = "ERR_SERVICE_STOP"

# --- 系统环境变量/注册表类 ---
ERR_SYS_ENV_GET = "ERR_SYS_ENV_GET"
ERR_SYS_ENV_INVALID_ACTION = "ERR_SYS_ENV_INVALID_ACTION"
ERR_SYS_ENV_INVALID_NAME = "ERR_SYS_ENV_INVALID_NAME"
ERR_SYS_ENV_INVALID_SCOPE = "ERR_SYS_ENV_INVALID_SCOPE"
ERR_SYS_ENV_INVALID_VALUE = "ERR_SYS_ENV_INVALID_VALUE"
ERR_SYS_ENV_LIST = "ERR_SYS_ENV_LIST"
ERR_SYS_REG_INVALID_ROOT_KEY = "ERR_SYS_REG_INVALID_ROOT_KEY"
ERR_SYS_REG_KEY_NOT_FOUND = "ERR_SYS_REG_KEY_NOT_FOUND"
ERR_SYS_REG_KEY_NOT_EMPTY = "ERR_SYS_REG_KEY_NOT_EMPTY"
ERR_SYS_REG_CANNOT_DELETE_ROOT = "ERR_SYS_REG_CANNOT_DELETE_ROOT"
ERR_SYS_REG_PERMISSION_DENIED = "ERR_SYS_REG_PERMISSION_DENIED"
ERR_REG_READ_FAILED = "ERR_REG_READ_FAILED"
ERR_REG_WRITE_FAILED = "ERR_REG_WRITE_FAILED"
ERR_REG_DELETE_FAILED = "ERR_REG_DELETE_FAILED"
ERR_REG_INVALID_PARAM = "ERR_REG_INVALID_PARAM"
ERR_REG_UNSUPPORTED_TYPE = "ERR_REG_UNSUPPORTED_TYPE"
ERR_REG_VALIDATE_FAILED = "ERR_REG_VALIDATE_FAILED"

# --- 桌面/GUI类 ---
ERR_DESKTOP_NOT_FOUND = "ERR_DESKTOP_NOT_FOUND"
ERR_FOCUS_WINDOW = "ERR_FOCUS_WINDOW"
ERR_GUI_CALL = "ERR_GUI_CALL"
ERR_WINDOW_LIST = "ERR_WINDOW_LIST"
ERR_WINDOW_NOT_FOUND = "ERR_WINDOW_NOT_FOUND"
ERR_WINDOW_RESIZE = "ERR_WINDOW_RESIZE"
ERR_WINDOW_SET_STATE = "ERR_WINDOW_SET_STATE"
ERR_SCREENSHOT = "ERR_SCREENSHOT"
ERR_SCREEN_RECORD = "ERR_SCREEN_RECORD"
ERR_SCREEN_SNAPSHOT = "ERR_SCREEN_SNAPSHOT"

# --- 数据库/SQL类 ---
ERR_SQL_EXEC = "ERR_SQL_EXEC"
ERR_DB_CONNECTION = "ERR_DB_CONNECTION"

# --- 数据格式解析类 ---
ERR_PARSE_YAML = "ERR_PARSE_YAML"
ERR_PARSE_TOML = "ERR_PARSE_TOML"
ERR_PARSE_INI = "ERR_PARSE_INI"
ERR_PARSE_XML = "ERR_PARSE_XML"
ERR_PARSE_JSON = "ERR_PARSE_JSON"
ERR_PARSE_PROPERTIES = "ERR_PARSE_PROPERTIES"
ERR_INVALID_JSON = "ERR_INVALID_JSON"
ERR_WRITE_YAML = "ERR_WRITE_YAML"
ERR_WRITE_TOML = "ERR_WRITE_TOML"
ERR_WRITE_JSON = "ERR_WRITE_JSON"
ERR_WRITE_DOCX = "ERR_WRITE_DOCX"
ERR_WRITE_XLSX = "ERR_WRITE_XLSX"
ERR_WRITE_PDF = "ERR_WRITE_PDF"

# --- 数据分析类 ---
ERR_DATA_ANALYSIS = "ERR_DATA_ANALYSIS"
ERR_STATISTICS_FAILED = "ERR_STATISTICS_FAILED"
ERR_SCHEMA_FAILED = "ERR_SCHEMA_FAILED"
ERR_FILTER_INVALID = "ERR_FILTER_INVALID"

# --- Agent/工具执行类 ---
ERR_TOOL_DEPRECATED = "ERR_TOOL_DEPRECATED"
ERR_TOOL_NOT_FOUND = "ERR_TOOL_NOT_FOUND"
ERR_MISSING_PARAM = "ERR_MISSING_PARAM"
ERR_UNKNOWN = "ERR_UNKNOWN"
ERR_UNSAFE_CODE = "ERR_UNSAFE_CODE"

# --- 其他 ---
ERR_INVALID_ACTION = "ERR_INVALID_ACTION"
ERR_INVALID_DIRECTION = "ERR_INVALID_DIRECTION"
ERR_INVALID_MODE = "ERR_INVALID_MODE"
ERR_INVALID_STEP = "ERR_INVALID_STEP"
ERR_INVALID_PARAMS = "ERR_INVALID_PARAMS"

# --- 迁移自动补充 ---
ERR_DESKTOP_CHECK_SCREEN_SIZE = "ERR_DESKTOP_CHECK_SCREEN_SIZE"
ERR_DESKTOP_CHECK_TESSERACT = "ERR_DESKTOP_CHECK_TESSERACT"
ERR_DESKTOP_CHECK_WINDOW = "ERR_DESKTOP_CHECK_WINDOW"
ERR_DESKTOP_CLIPBOARD = "ERR_DESKTOP_CLIPBOARD"
ERR_DESKTOP_GET_MOUSE_POSITION = "ERR_DESKTOP_GET_MOUSE_POSITION"
ERR_DESKTOP_GET_WINDOW_INFO = "ERR_DESKTOP_GET_WINDOW_INFO"
ERR_DESKTOP_GET_WINDOW_POSITION = "ERR_DESKTOP_GET_WINDOW_POSITION"
ERR_DESKTOP_MOUSE_CLICK = "ERR_DESKTOP_MOUSE_CLICK"
ERR_DESKTOP_MOUSE_SCROLL = "ERR_DESKTOP_MOUSE_SCROLL"
ERR_DESKTOP_NOT_WINDOWS = "ERR_DESKTOP_NOT_WINDOWS"
ERR_DESKTOP_NO_DEPENDENCY = "ERR_DESKTOP_NO_DEPENDENCY"
ERR_DESKTOP_PLATFORM_NOT_SUPPORTED = "ERR_DESKTOP_PLATFORM_NOT_SUPPORTED"
ERR_DOC_ANALYZE_DATA = "ERR_DOC_ANALYZE_DATA"
ERR_DOC_CHART_GENERATE = "ERR_DOC_CHART_GENERATE"
ERR_DOC_CONVERT_FAILED = "ERR_DOC_CONVERT_FAILED"
ERR_DOC_DATA_FORMAT_FAILED = "ERR_DOC_DATA_FORMAT_FAILED"
ERR_DOC_DB_TABLE_NOT_FOUND = "ERR_DOC_DB_TABLE_NOT_FOUND"
ERR_DOC_FORMAT_NOT_DETECTED = "ERR_DOC_FORMAT_NOT_DETECTED"
ERR_DOC_NO_OPENPYXL = "ERR_DOC_NO_OPENPYXL"
ERR_DOC_NO_PPTX = "ERR_DOC_NO_PPTX"
ERR_DOC_QUERY_EMPTY = "ERR_DOC_QUERY_EMPTY"
ERR_DOC_READ_CSV = "ERR_DOC_READ_CSV"
ERR_DOC_READ_DOCX = "ERR_DOC_READ_DOCX"
ERR_DOC_READ_PDF = "ERR_DOC_READ_PDF"
ERR_DOC_READ_PPTX = "ERR_DOC_READ_PPTX"
ERR_DOC_READ_XLSX = "ERR_DOC_READ_XLSX"
ERR_DOC_WRITE_PPTX = "ERR_DOC_WRITE_PPTX"
ERR_EXEC_FAILED = "ERR_EXEC_FAILED"
ERR_EXEC_JS = "ERR_EXEC_JS"
ERR_EXEC_PYTHON = "ERR_EXEC_PYTHON"
ERR_EXEC_TIMEOUT = "ERR_EXEC_TIMEOUT"
ERR_FILE_BACKUP = "ERR_FILE_BACKUP"
ERR_FILE_CALCULATE_DISTRIBUTION = "ERR_FILE_CALCULATE_DISTRIBUTION"
ERR_FILE_CHECKSUM_FAILED = "ERR_FILE_CHECKSUM_FAILED"
ERR_FILE_CHECKSUM_TIMEOUT = "ERR_FILE_CHECKSUM_TIMEOUT"
ERR_FILE_CHECK_PERMISSION = "ERR_FILE_CHECK_PERMISSION"
ERR_FILE_COMPRESS_FAILED = "ERR_FILE_COMPRESS_FAILED"
ERR_FILE_CONTENT_BLOCKED = "ERR_FILE_CONTENT_BLOCKED"
ERR_FILE_CONTENT_SEARCH_FAILED = "ERR_FILE_CONTENT_SEARCH_FAILED"
ERR_FILE_COPY_FAILED = "ERR_FILE_COPY_FAILED"
ERR_FILE_CREATE_DIR = "ERR_FILE_CREATE_DIR"
ERR_FILE_DELETE_FAILED = "ERR_FILE_DELETE_FAILED"
ERR_FILE_EDIT_FAILED = "ERR_FILE_EDIT_FAILED"
ERR_FILE_ENCODING = "ERR_FILE_ENCODING"
ERR_FILE_EXTRACT = "ERR_FILE_EXTRACT"
ERR_FILE_HASH = "ERR_FILE_HASH"
ERR_FILE_INFO = "ERR_FILE_INFO"
ERR_FILE_LIST_DIR_FAILED = "ERR_FILE_LIST_DIR_FAILED"
ERR_FILE_METADATA = "ERR_FILE_METADATA"
ERR_FILE_MIME_TYPE = "ERR_FILE_MIME_TYPE"
ERR_FILE_MOVE_FAILED = "ERR_FILE_MOVE_FAILED"
ERR_FILE_MOVE_TRASH = "ERR_FILE_MOVE_TRASH"
ERR_FILE_PATH_EXISTS = "ERR_FILE_PATH_EXISTS"
ERR_FILE_PATH_NOT_FILE = "ERR_FILE_PATH_NOT_FILE"
ERR_KEYBOARD_SHORTCUT = "ERR_KEYBOARD_SHORTCUT"
ERR_KEYBOARD_TYPE = "ERR_KEYBOARD_TYPE"
ERR_KEY_COMBO = "ERR_KEY_COMBO"
ERR_META_CALENDAR_NEXT_N_WORKDAY = "ERR_META_CALENDAR_NEXT_N_WORKDAY"
ERR_META_INVALID_CHECK_TYPE = "ERR_META_INVALID_CHECK_TYPE"
ERR_META_TIME_CONVERT = "ERR_META_TIME_CONVERT"
ERR_META_TIME_FORMAT = "ERR_META_TIME_FORMAT"
ERR_META_TOOL_IMPL_NOT_FOUND = "ERR_META_TOOL_IMPL_NOT_FOUND"
ERR_MISSING_TOOL = "ERR_MISSING_TOOL"
ERR_NETWORK_CONNECTION_ERROR = "ERR_NETWORK_CONNECTION_ERROR"
ERR_NETWORK_CREATE_DIR = "ERR_NETWORK_CREATE_DIR"
ERR_NETWORK_DNS_ERROR = "ERR_NETWORK_DNS_ERROR"
ERR_NETWORK_DOWN = "ERR_NETWORK_DOWN"
ERR_NETWORK_HTTP_ERROR = "ERR_NETWORK_HTTP_ERROR"
ERR_NETWORK_INVALID_HOST = "ERR_NETWORK_INVALID_HOST"
ERR_NETWORK_INVALID_PARAM = "ERR_NETWORK_INVALID_PARAM"
ERR_NETWORK_INVALID_PATH = "ERR_NETWORK_INVALID_PATH"
ERR_NETWORK_INVALID_PORT = "ERR_NETWORK_INVALID_PORT"
ERR_NETWORK_JS_RENDER = "ERR_NETWORK_JS_RENDER"
ERR_NETWORK_REQUEST_ERROR = "ERR_NETWORK_REQUEST_ERROR"
ERR_NETWORK_WRITE_FILE = "ERR_NETWORK_WRITE_FILE"
ERR_NET_UNKNOWN = "ERR_NET_UNKNOWN"
ERR_NO_DOCX = "ERR_NO_DOCX"
ERR_NO_IMAGEIO = "ERR_NO_IMAGEIO"
ERR_NO_LIBREOFFICE = "ERR_NO_LIBREOFFICE"
ERR_NO_MATCH = "ERR_NO_MATCH"
ERR_NO_MATPLOTLIB = "ERR_NO_MATPLOTLIB"
ERR_NO_NUMPY = "ERR_NO_NUMPY"
ERR_NO_PANDAS = "ERR_NO_PANDAS"
ERR_NO_PDFPLUMBER = "ERR_NO_PDFPLUMBER"
ERR_NO_PYAUTOGUI = "ERR_NO_PYAUTOGUI"
ERR_NO_PYYAML = "ERR_NO_PYYAML"
ERR_NO_RECORD_LIB = "ERR_NO_RECORD_LIB"
ERR_NO_REPORTLAB = "ERR_NO_REPORTLAB"
ERR_NO_SCREENSHOT_LIB = "ERR_NO_SCREENSHOT_LIB"
ERR_NO_TESSERACT = "ERR_NO_TESSERACT"
ERR_NO_TOMLI = "ERR_NO_TOMLI"
ERR_NO_TOMLI_W = "ERR_NO_TOMLI_W"
ERR_OCR = "ERR_OCR"
ERR_PARAM_MISMATCH = "ERR_PARAM_MISMATCH"
ERR_PATH_INVALID = "ERR_PATH_INVALID"
ERR_PATH_NOT_FILE = "ERR_PATH_NOT_FILE"
ERR_PERMISSION_DENIED = "ERR_PERMISSION_DENIED"
ERR_PIPELINE_FAILED = "ERR_PIPELINE_FAILED"
ERR_PIPELINE_STOPPED = "ERR_PIPELINE_STOPPED"
ERR_PIPELINE_TIMEOUT = "ERR_PIPELINE_TIMEOUT"
ERR_QUERY_FAILED = "ERR_QUERY_FAILED"
ERR_READ_CSV_BASIC = "ERR_READ_CSV_BASIC"
ERR_READ_CSV_DATAFRAME = "ERR_READ_CSV_DATAFRAME"
ERR_READ_EXCEL_DATAFRAME = "ERR_READ_EXCEL_DATAFRAME"
ERR_READ_ONLY_VIOLATION = "ERR_READ_ONLY_VIOLATION"
ERR_REG_PERMISSION_DENIED = "ERR_REG_PERMISSION_DENIED"

# --- 迁移自动补充 ---
ERR_DESKTOP_NO_PYWIN32 = "ERR_DESKTOP_NO_PYWIN32"
ERR_NO_WIN10TOAST = "ERR_NO_WIN10TOAST"
ERR_NO_WIN32GUI = "ERR_NO_WIN32GUI"

# ============================================================
# 9. 会话与缓存（从 message_saver/display_name_cache 迁移）
# ============================================================

INVALID_SESSION_IDS_MAX = 500
MAX_CACHE_SIZE = 1000

# ============================================================
# 10. LLM解析器工具名/参数名降级映射（从 llm_response_parser 迁移）
# ============================================================

TOOL_NAME_FALLBACK_KEYS = ["action", "action_tool", "tool_name"]
TOOL_PARAMS_FALLBACK_KEYS = ["params", "action_input", "actionInput"]

# ============================================================
# 11. SSE流超时（从 react_sse_wrapper 迁移）
# ============================================================

from datetime import timedelta
TASK_TIMEOUT = timedelta(hours=1)

# ============================================================
# 12. Agent meta工具（从 base_react.py 迁移）
# ============================================================

META_TOOL_NAMES = [
    'tool_help', 'tool_search', 'pipeline',
    'get_time', 'time_add', 'time_diff', 'query_calendar', 'timezone_convert',
    'batch_process', 'timer',
]

# ============================================================
# 13. CRSS意图配置（从 task_tracker.py 迁移）
# ============================================================

VALID_INTENTS = {
    "file", "shell", "document", "code_execution",
    "network", "system", "desktop", "time", "meta",
}

# ============================================================
# 14. CRSS置信度阈值（从 crss_scorer.py 迁移）
# ============================================================

CRSS_CONFIDENCE_THRESHOLD = 0.3

# ============================================================
# 15. CRSS评分权重（从 parse_scope/target/operation 迁移）
# ============================================================

SCOPE_MULTIPLIERS = {
    'SINGLE_FILE': 1.1,
    'DIRECTORY': 1.45,
    'CROSS_DIR': 1.5,
    'SYSTEM': 3.0,
}

SCOPE_PATTERNS = {
    'SINGLE_FILE': [r'^[^*?]+\.[a-zA-Z0-9]+$', r'^[^*?/]+$'],
    'DIRECTORY': [r'[/\\]$', r'\$'],
    'CROSS_DIR': [r'\*', r'\?'],
    'SYSTEM': [r'^-rf$', r'^/s$', r'^/q$', r'^C:\\$', r'^/$'],
}

TARGET_WEIGHTS = {
    'TEMP': {'min': 0, 'max': 4, 'default': 3, 'patterns': [r'\.tmp$', r'\.cache', r'^temp[/\\]', r'temp[/\\]', r'\.log$', r'log[/\\]', r'\*.tmp']},
    'USER': {'min': 3, 'max': 5, 'default': 4, 'patterns': [r'~/', r'/home/', r'文档[/\\]', r'用户', r'documents', r'users?[/\\]']},
    'PROJECT': {'min': 3, 'max': 6, 'default': 3, 'patterns': [r'src[/\\]', r'app[/\\]', r'backend[/\\]', r'frontend[/\\]', r'\.py', r'\.js', r'\.ts', r'tests[/\\]', r'config[/\\]', r'\.git']},
    'SYSTEM': {'min': 8, 'max': 10, 'default': 9, 'patterns': [r'C:\\Windows', r'/bin', r'/etc', r'/sbin', r'/usr', r'系统', r'windows[/\\]system32', r'registry', r'密码', r'shadow', r'passwd', r'SAM', r'配置', r'注册表']},
}

OPERATION_WEIGHTS = {
    'READ': {'min': 0, 'max': 2, 'default': 1, 'keywords': ['cat', 'ls', 'grep', '查看', '读取', 'type', 'dir', '运行']},
    'CREATE': {'min': 2, 'max': 4, 'default': 3, 'keywords': ['mkdir', 'touch', '创建', '新建', 'md']},
    'UPDATE': {'min': 4, 'max': 7, 'default': 5, 'keywords': ['edit', 'sed', '修改', '编辑', '更新', 'echo', 'write']},
    'DELETE': {'min': 6, 'max': 10, 'default': 8, 'keywords': ['rm', 'del', 'delete', '删除', 'remove', '清除', 'rmdir', 'rd']},
    'COPY': {'min': 2, 'max': 5, 'default': 3, 'keywords': ['copy', 'cp', '复制', '拷贝']},
    'MOVE': {'min': 2, 'max': 5, 'default': 3, 'keywords': ['move', 'mv', '移动']},
    'EXEC': {'min': 5, 'max': 10, 'default': 7, 'keywords': ['sudo', 'run', 'exec', '执行', 'start']},
}
